---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: arane-site
spec:
  encryptedData:
    .dockerconfigjson: AgCGkszOX2NbW/w/WyMiX9TUEFgEAqGlM4kgorygce62OrRGOrQprPmHyoVsseGOG0AR5tCpYnF7pEAFP1ezP7Nax/w16iNUx0pboQbpD5AoZGHYCecBYUE4jTmwba04eYQwANV1MuWYakJBAdkR+vlnsSmF7CitvkoS6jiB47gy0DZ6P1Y8ou1v50d5UV97elv8YAyN77SU8RByODYH8lmXsZU0UPKjut8rTyCgYL2/BpiKDN85wW6q89K4yt05nq4f2tcJFUqV+GPr05VyPeiu4D8e6JIy+B7Zcladc40m8CfHvNO060CCV0fr86sgx253UjaUsVOlorVD55VQ/kr0j6R0GrD/H9H9rdFeQ6kQWSo0TABkAB2TcyJX6lPxtSGHgcaJ5d4CFEDhsNxsDPhb0t7w0O1NgEdjSsdmABAtwfqUeOxo71oGeL5l6GJZlI8pHgTft89/PL42eCsutdBM3X+uw/4xh4PRVIxZx0Bva/R2uAVTHutdTVxThdXGSOxZMQIETI+yhoIzrEbDlX2MNUtPB8biR6zLBKq3C5ARmuOad6pI+C/3LWFyTzrUjeZly8vmdmCT0BzOFfDA/BFCfgQjX6tdNENmnLXK/28Sz5pzRUOG5larQnsQPgOJqkfimUeOtV3cs8ov0kkla0H8eIVXvKckA0wTf16P8RGuv09XP3g3sA2lrZtwxflZbTv+YR4eiq0FZ3t5qOlFyA3JvtRIyeV9Ax5503q2kWUWCl7hFCxU8qlyPRk7CXUMO4b0IHjDl2iaFu++pCRvoV8jeKXmWfhDBWpd8Pm4kMI3Th2ltcUNoCc2R2H34wbTSdmmFH9nFPYKtVWXc45ArwTAH99YB+wd/xzLrDqBW5AwtqUYRUHsvnDerhjwCIzAOqMj/yBfARosxZlo3yGqpIhPrwLTxcmmg6NCUCJGfjGKAUYdjv6YMztyptmK+ZCL0GJ3KCU8+FwOfa6MqHDE6F5joSIo+DLNGqQQ+lQuvx5pNxkpfRIz2+lq5GPzZsEgLFd2LRfjeoeA792VOLIcWdCO6G1lovotuwGNKGcffA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: arane-site
    type: kubernetes.io/dockerconfigjson
