import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { siteTitle } from "../site-config";
import { GoogleAnalytics } from "@next/third-parties/google";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: siteTitle,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        {children}
        <footer className="p-4 bg-gray-800 text-white text-center">
          <p>&copy; 2024-2025 ramura, Yuito Akatsuki, Mitsuru Akatsuki(Design)</p>
        </footer>
      </body>
      <GoogleAnalytics gaId={"G-301PMSJ9EB"} />
    </html>
  );
}
