import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {siteTitle} from "../site-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: siteTitle,
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <nav className="flex items-center justify-between p-4">
            <a href="/">
              <h1 className="text-2xl font-bold">{siteTitle}</h1>
            </a>
            <ul className="flex space-x-4">
              <li>
                <a href="/about">About</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className="p-4 bg-gray-800 text-white text-center">
          <p>&copy; Yuito Akatsuki 2024, ramura 2024</p>
        </footer>
      </body>
    </html>
  );
}
