apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramura-site
spec:
  selector:
    matchLabels:
      app: arane
  template:
    metadata:
      labels:
        app: arane
    spec:
      containers:
        - name: app
          image: registry.uniproject-tech.net/arane-site:beta
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: zip-pvc
              mountPath: /nextjs/public/assets
      volumes:
        - name: zip-pvc
          persistentVolumeClaim:
            claimName: zip
---
apiVersion: v1
kind: Service
metadata:
  name: ramura-site
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: arane
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
