apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramura-site
spec:
  selector:
    matchLabels:
      app: ramura-site
  template:
    metadata:
      labels:
        app: ramura-site
    spec:
      containers:
      - name: app
        image: localhost:32000/arane-site:1.4.2
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
            
---
apiVersion: v1
kind: Service
metadata:
  name: ramura-site
spec:
  selector:
    app: ramura-site
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
