name: Auto Version Tag
on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  Tagging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.NPM_VERSIONER_APP_ID }}
          private-key: ${{ secrets.NPM_VERSIONER_PRIVATE_KEY }}
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
      
      - name: git setting
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: npm tag(Major)
        if: contains(github.event.pull_request.labels.*.name, 'PR:major')
        run: |
          npm version premajor
      
      - name: npm tag(Minor)
        if: contains(github.event.pull_request.labels.*.name, 'PR:minor')
        run: |
          npm version preminor
      
      - name: npm tag(Patch)
        if: contains(github.event.pull_request.labels.*.name, 'PR:patch')
        run: |
          npm version prepatch
      
      - name: npm tag(release)
        if: contains(github.event.pull_request.labels.*.name, 'PR:release')
        run: |
          npm version prerelease

      - name: Push
        run: |
          git push --all
          git push --tags