name: Docker Build and Push
on:
  push:
    branches:
      - main

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.K8S_DOCKER_REGISTHOST }}/arane-site:latest .
        id: build

      - name: Push Docker image
        run: docker push ${{ secrets.K8S_DOCKER_REGISTHOST }}/arane-site:latest