name: Auto Version Tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Tagging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: git setting
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: npm tag(Major)
        if: contains(github.event.pull_request.labels.*.name, 'PR:major')
        run: |
          npm version major
      
      - name: npm tag(Minor)
        if: contains(github.event.pull_request.labels.*.name, 'PR:minor')
        run: |
          npm version minor
      
      - name: npm tag(Patch)
        if: contains(github.event.pull_request.labels.*.name, 'PR:patch')
        run: |
          npm version patch
        
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop branch
        run: git checkout dev

      - name: Rebase onto main
        run: |
          git rebase origin/main || echo "::error::Rebase failed. Please resolve conflicts manually."

      - name: Send Discord Notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "embeds": [
                      {
                        "title": "🚨 Rebase Conflict Detected!",
                        "description": "A rebase conflict occurred in the `develop` branch after merging into `main`. Please resolve it manually.",
                        "url": "https://github.com/UniPro-tech/ramura-utau-site",
                        "color": 16711680,
                        "fields": [
                          {
                            "name": "Branch",
                            "value": "`develop`"
                          },
                          {
                            "name": "Action Required",
                            "value": "Manual conflict resolution needed."
                          }
                        ],
                        "footer": {
                          "text": "GitHub Actions Notification"
                        },
                        "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
                      }
                    ]
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Push changes
        run: |
          git push --all
          git push --tags
          git reset --merge
          git checkout main
          git push --all
