name: Auto Version Tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Tagging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine version bump
        id: version_bump
        run: |
          if [[ $(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH) == *"major"* ]]; then
            echo "::set-output name=version::major"
          elif [[ $(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH) == *"minor"* ]]; then
            echo "::set-output name=version::minor"
          elif [[ $(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH) == *"patch"* ]]; then
            echo "::set-output name=version::patch"
          else
            echo "No version label found"
            exit 1
          fi

      - name: npm tag
        run: |
          npm version ${{ steps.version_bump.outputs.version }}
          git push --follow-tags
      
      - name: Rebase develop
        run: |
          git checkout develop
          git pull
          git rebase main
          git push
